# Copyright 2020 The Kubermatic Kubernetes Platform contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kube-state-metrics:
  fullnameOverride: kube-state-metrics

  # list of image pull secret references, e.g.
  # imagePullSecrets:
  #   - name: registry-k8s-io-pull-secret
  imagePullSecrets: []
  resources:
    requests:
      # Rationalized based on real world usage
      cpu: 3m
      memory: 128Mi
    limits:
      cpu: 2
      memory: 384Mi

  # List of additional cli arguments to configure kube-state-metrics
  # for example: --enable-gzip-encoding, --log-file, etc.
  # all the possible args can be found here: https://github.com/kubernetes/kube-state-metrics/blob/main/docs/developer/cli-arguments.md
  extraArgs:
  - --metric-labels-allowlist=pods=[app.kubernetes.io/name,app.kubernetes.io/component,app.kubernetes.io/instance,component,part-of,app,unit],deployments=[app.kubernetes.io/name,app.kubernetes.io/component,app.kubernetes.io/instance],persistentvolumeclaims=[excluded-from-alerts]

  podAnnotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
    fluentbit.io/parser: glog
    cluster-autoscaler.kubernetes.io/safe-to-evict-local-volumes: tmp

  serviceAccount:
    # If false then the user will opt out of automounting API credentials.
    automountServiceAccountToken: false

  rbac:
    # Add permissions for CustomResources' apiGroups in Role/ClusterRole. Should be used in conjunction with Custom Resource State Metrics configuration
    # Example:
    # - apiGroups: ["monitoring.coreos.com"]
    #   resources: ["prometheuses"]
    #   verbs: ["list", "watch"]
    extraRules: []

  # Enabling support for customResourceState, will create a configMap including your config that will be read from kube-state-metrics
  customResourceState:
    enabled: false
    # Add ClusterRole permissions to list/watch the customResources defined in the config to rbac.extraRules
    config: {}

  nodeSelector: {}
  
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app: kube-state-metrics
          topologyKey: kubernetes.io/hostname
        weight: 100
  
  tolerations: []

  # Ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/
  podDisruptionBudget:
    maxUnavailable: 1

  volumes:
  - name: tmp
    emptyDir: {}

  volumeMounts:
  - name: tmp
    mountPath: /tmp

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsUser: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    enabled: false

  selfMonitor:
    enabled: true

  # Enable vertical pod autoscaler support for kube-state-metrics
  verticalPodAutoscaler:
    enabled: false

    # Recommender responsible for generating recommendation for the object.
    # List should be empty (then the default recommender will generate the recommendation)
    # or contain exactly one recommender.
    # recommenders: []
    # - name: custom-recommender-performance

    # List of resources that the vertical pod autoscaler can control. Defaults to cpu and memory
    controlledResources: []
    # Specifies which resource values should be controlled: RequestsOnly or RequestsAndLimits.
    # controlledValues: RequestsAndLimits

    # Define the max allowed resources for the pod
    maxAllowed: {}
    # cpu: 200m
    # memory: 100Mi
    # Define the min allowed resources for the pod
    minAllowed: {}
    # cpu: 200m
    # memory: 100Mi

    # updatePolicy:
      # Specifies minimal number of replicas which need to be alive for VPA Updater to attempt pod eviction
      # minReplicas: 1
      # Specifies whether recommended updates are applied when a Pod is started and whether recommended updates
      # are applied during the life of a Pod. Possible values are "Off", "Initial", "Recreate", and "Auto".
      # updateMode: Auto